image: node:latest

stages:
  - build
  - test
cache:
  paths:
    - node_modules/

build:
  stage: build
  tags:
    - docker
  script:
    - npm install
    - npm build

test:
  stage: test
  tags:
    - docker
  script:
    - echo "----- Test Running -----"
